/* Vastunest Realty: static Pages CMS bridge. Reads Markdown files from content/projects. */
const OWNER = "vastunestrealty";
const REPO = "vastunestrealty";
const BRANCH = "main";
const PROJECTS_PATH = "content/projects";
const FALLBACK_PROJECTS = [
  {title:"Yashada Evo, Punawale",slug:"yashada-evo-punawale",location:"Punawale, Pune",bhk:"2 BHK, 3 BHK homes",starting_price:10000000,property_type:"Apartment",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",description:"Explore a contemporary residential address in Punawale. Contact Vastunest Realty for the latest availability, pricing and project details."}
];
let projects = [];
const $ = (s)=>document.querySelector(s);
const safe = (v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function money(v){const n=Number(String(v??"").replace(/[₹,\s]/g,""));if(!Number.isFinite(n)||n<=0)return "Price on request";if(n>=10000000){const cr=n/10000000;return "₹"+(Number.isInteger(cr)?cr:cr.toFixed(2).replace(/0+$/,"").replace(/\.$/,""))+" Cr";}if(n>=100000)return "₹"+(n/100000).toFixed(n%100000===0?0:1)+" L";return "₹"+n.toLocaleString("en-IN");}
function parseScalar(v){v=(v||"").trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(v==="true")return true;if(v==="false")return false;if(/^\d+(\.\d+)?$/.test(v))return Number(v);if(v.startsWith("[")&&v.endsWith("]"))return v.slice(1,-1).split(",").map(x=>parseScalar(x));return v;}
function parseMarkdown(md,filename){const lines=md.split(/\r?\n/);let data={},body=md;if(lines[0]?.trim()==="---"){const end=lines.indexOf("---",1);if(end>0){body=lines.slice(end+1).join("\n");let key=null;for(const line of lines.slice(1,end)){const m=line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);if(m){key=m[1];data[key]=parseScalar(m[2]);}else if(key&&/^\s+-\s+/.test(line)){if(!Array.isArray(data[key]))data[key]=[];data[key].push(parseScalar(line.replace(/^\s+-\s+/,"")));}}}}data.description=data.description||body.replace(/^#+.*$/gm,"").trim().slice(0,350);data.title=data.title||data.name||filename.replace(/\.md$/,"").replace(/-/g," ");data.slug=data.slug||filename.replace(/\.md$/,"");return data;}
async function loadProjects(){try{const url=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PROJECTS_PATH}?ref=${BRANCH}`;const r=await fetch(url,{headers:{"Accept":"application/vnd.github+json"}});if(!r.ok)throw Error("Projects folder not available");const list=await r.json();const mdFiles=list.filter(f=>f.type==="file"&&f.name.endsWith(".md"));const loaded=await Promise.all(mdFiles.map(async f=>{const rr=await fetch(f.download_url);if(!rr.ok)return null;return parseMarkdown(await rr.text(),f.name)}));projects=loaded.filter(p=>p&&String(p.draft)!=="true");if(!projects.length)projects=FALLBACK_PROJECTS;}catch(e){console.info("Using starter project while CMS files are unavailable:",e.message);projects=FALLBACK_PROJECTS;}populateLocations();renderProjects();}
function populateLocations(){const select=$("#locationFilter");const current=select.value;const locations=[...new Set(projects.map(p=>p.location||p.area).filter(Boolean))].sort();select.innerHTML='<option value="">All locations</option>'+locations.map(l=>`<option value="${safe(l)}">${safe(l)}</option>`).join("");select.value=current;}
function matchesBhk(p,bhk){if(!bhk)return true;return String(p.bhk||p.configuration||"").toLowerCase().includes(bhk.toLowerCase());}
function renderProjects(){const loc=$("#locationFilter").value,bhk=$("#bhkFilter").value,budget=$("#budgetFilter").value;let [min,max]=budget?budget.split("-").map(Number):[0,Infinity];const filtered=projects.filter(p=>(!loc||(p.location||p.area)===loc)&&matchesBhk(p,bhk)&&(!budget||(Number(p.starting_price||p.price||0)>=min&&Number(p.starting_price||p.price||0)<max)));$("#resultsCount").textContent=`${filtered.length} ${filtered.length===1?"property":"properties"} to explore`;$("#emptyState").hidden=filtered.length>0;$("#projectGrid").innerHTML=filtered.map((p,i)=>{const image=p.image||p.cover_image||p.featured_image||"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80";const title=p.title||p.name||"Featured Property";const location=p.location||p.area||"Pune";const config=p.bhk||p.configuration||p.property_type||"Residential";const price=p.starting_price||p.price||"";return `<article class="project-card"><div class="project-image"><img src="${safe(image)}" alt="${safe(title)}" loading="lazy" onerror="this.src='https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80'"><span class="project-tag">${safe(p.property_type||"Featured Residence")}</span></div><div class="project-content"><div class="project-location">${safe(location)}</div><h3>${safe(title)}</h3><div class="project-meta"><span>${safe(config)}</span>${p.developer?`<span>${safe(p.developer)}</span>`:""}</div><div class="project-bottom"><div><span class="price-label">Starting from</span><span class="project-price">${safe(money(price))}</span></div><a href="#" class="card-link" data-project="${safe(p.slug||title)}">View details ↗</a></div></div></article>`}).join("");document.querySelectorAll("[data-project]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();const p=projects.find(x=>(x.slug||x.title||x.name)===a.dataset.project);if(p)openDetails(p)});}
function openDetails(p){const modal=document.createElement("div");modal.className="detail-modal open";modal.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true" aria-label="${safe(p.title||p.name)} details"><button class="modal-close" aria-label="Close">×</button><p class="eyebrow">VASTUNEST PROPERTY DETAILS</p><h2>${safe(p.title||p.name)}</h2><p>${safe(p.description||"Contact our property advisor for detailed project information.")}</p><div class="modal-details"><div><small>Location</small><strong>${safe(p.location||p.area||"Pune")}</strong></div><div><small>Configuration</small><strong>${safe(p.bhk||p.configuration||"On request")}</strong></div><div><small>Starting price</small><strong>${safe(money(p.starting_price||p.price))}</strong></div><div><small>Developer</small><strong>${safe(p.developer||"Details on request")}</strong></div></div><div class="modal-actions"><a href="https://wa.me/?text=${encodeURIComponent("Hello Vastunest Realty, please share details for "+(p.title||p.name)+".")}" target="_blank" rel="noopener">Enquire on WhatsApp ↗</a><a href="mailto:hello@vastunestrealty.com?subject=${encodeURIComponent("Property enquiry: "+(p.title||p.name))}">Email an advisor ↗</a></div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector(".modal-close").addEventListener("click",close);modal.addEventListener("click",e=>{if(e.target===modal)close()});document.addEventListener("keydown",function esc(e){if(e.key==="Escape"){close();document.removeEventListener("keydown",esc)}});}
$("#searchButton").addEventListener("click",renderProjects);["locationFilter","bhkFilter","budgetFilter"].forEach(id=>$("#"+id).addEventListener("change",renderProjects));$("#menuToggle").addEventListener("click",()=>$("#navLinks").classList.toggle("open"));document.querySelectorAll("#navLinks a").forEach(a=>a.addEventListener("click",()=>$("#navLinks").classList.remove("open")));$("#year").textContent=new Date().getFullYear();loadProjects();
